spring:
  application:
    name: openfeign
eureka:
  instance:
    hostname: 192.168.1.3
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8200/eureka/

feign:
  hystrix:
    enabled: true
