spring:
  application:
    name: zuul
eureka:
  instance:
    hostname: 192.168.1.103
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8200/eureka/

zuul:
  routes:
    basic:
      path: /**
      serviceId: openfeign