spring:
  application:
    name: aoyoxOpenFeign
eureka:
  instance:
    hostname: 192.168.1.103
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8200/eureka/

feign:
  hystrix:
    enabled: false
