version: '3.3'
services:
  aoyoxBack:
    image: mar105/ubuntu-tomcat9-jdk12:latest
    container_name: aoyoxBack
    ports:
      - 8200:8080
    restart: always
    volumes:
      - /Users/yanghenglin/Desktop/mar105/aoyox/aoyoxBack/build/libs/aoyoxBack.war:/mar105/apache-tomcat-9.0.21/webapps/ROOT.war
    healthcheck:
      test: "/bin/netstat -anp | grep 8200"
      interval: 10s
      timeout: 3s
      retries: 1
    entrypoint: '/mar105/apache-tomcat-9.0.21/bin/catalina.sh run'

  aoyoxConfigServer:
    image: mar105/ubuntu-tomcat9-jdk12:latest
    container_name: aoyoxConfigServer
    ports:
      - 8201:8080
    restart: always
    volumes:
      - /Users/yanghenglin/Desktop/mar105/aoyox/aoyoxConfigServer/build/libs/aoyoxConfigServer.war:/mar105/apache-tomcat-9.0.21/webapps/ROOT.war
    depends_on:
      - aoyoxBack
    entrypoint:  /entrypoint.sh -d 192.168.1.103:8200 -c '/mar105/apache-tomcat-9.0.21/bin/catalina.sh run'
      
  aoyoxZuul:
    image: mar105/ubuntu-tomcat9-jdk12:latest
    container_name: aoyoxZuul
    ports:
      - 8202:8080
    restart: always
    volumes:
      - /Users/yanghenglin/Desktop/mar105/aoyox/aoyoxZuul/build/libs/aoyoxZuul.war:/mar105/apache-tomcat-9.0.21/webapps/ROOT.war
    depends_on:
      - aoyoxConfigServer
    entrypoint: /entrypoint.sh -d 192.168.1.103:8201 -c '/mar105/apache-tomcat-9.0.21/bin/catalina.sh run'
    
  aoyoxOpenFeign:
    image: mar105/ubuntu-tomcat9-jdk12:latest
    container_name: aoyoxOpenFeign
    ports:
      - 8210:8080
    restart: always
    volumes:
      - /Users/yanghenglin/Desktop/mar105/aoyox/aoyoxOpenFeign/build/libs/aoyoxOpenFeign.war:/mar105/apache-tomcat-9.0.21/webapps/ROOT.war
    depends_on:
      - aoyoxConfigServer
    entrypoint: /entrypoint.sh -d 192.168.1.103:8201 -c '/mar105/apache-tomcat-9.0.21/bin/catalina.sh run'

  aoyoxBasic:
    image: mar105/ubuntu-tomcat9-jdk12:latest
    container_name: aoyoxBasic
    ports:
      - 8211:8080
    restart: always
    volumes:
      - /Users/yanghenglin/Desktop/mar105/aoyox/aoyoxBasic/build/libs/aoyoxBasic.war:/mar105/apache-tomcat-9.0.21/webapps/ROOT.war
    depends_on:
      - aoyoxConfigServer
    entrypoint: /entrypoint.sh -d 192.168.1.103:8210 -c '/mar105/apache-tomcat-9.0.21/bin/catalina.sh run'


