version: '3.3'
services:
  aoyoxBack:
    image: mar105/ubuntu-tomcat9-jdk12:latest
    container_name: aoyoxBack
    ports:
      - 8200:8080
    restart: always
    volumes:
      - /Users/yanghenglin/Desktop/mar105/aoyox/aoyoxBack/build/libs/:/mar105/apache-tomcat-9.0.21/webapps
    healthcheck:
      test: "/bin/netstat -anp | grep 8200"
      interval: 10s
      timeout: 3s
      retries: 1
  aoyoxConfigServer:
    image: mar105/ubuntu-tomcat9-jdk12:latest
    container_name: aoyoxConfigServer
    ports:
      - 8201:8080
    restart: always
    volumes:
      - /Users/yanghenglin/Desktop/mar105/aoyox/aoyoxConfigServer/build/libs:/mar105/apache-tomcat-9.0.21/webapps
    depends_on:
      - aoyoxBack

  aoyoxZuul:
    image: mar105/ubuntu-tomcat9-jdk12:latest
    container_name: aoyoxZuul
    ports:
    - 8202:8080
    restart: always
    volumes:
    - /Users/yanghenglin/Desktop/mar105/aoyox/aoyoxZuul/build/libs:/mar105/apache-tomcat-9.0.21/webapps
    depends_on:
    - aoyoxConfigServer

  aoyoxOpenFeign:
    image: mar105/ubuntu-tomcat9-jdk12:latest
    container_name: aoyoxOpenFeign
    ports:
    - 8210:8080
    restart: always
    volumes:
    - /Users/yanghenglin/Desktop/mar105/aoyox/aoyoxOpenFeign/build/libs:/mar105/apache-tomcat-9.0.21/webapps
    depends_on:
    - aoyoxConfigServer

  aoyoxBasic:
    image: mar105/ubuntu-tomcat9-jdk12:latest
    container_name: aoyoxBasic
    ports:
    - 8212:8080
    restart: always
    volumes:
    - /Users/yanghenglin/Desktop/mar105/aoyox/aoyoxBasic/build/libs:/mar105/apache-tomcat-9.0.21/webapps
    depends_on:
    - aoyoxConfigServer
